/* eslint-disable @typescript-eslint/no-require-imports */
/**
 * AUTO-GENERATED by scripts/download-curriculum-assets.mjs — do not edit by hand.
 * Maps original curriculum HTTPS URLs to bundled static assets for offline display.
 */

export const CURRICULUM_ASSET_MAP: Record<string, number> = {
  "https://upload.wikimedia.org/wikipedia/commons/1/16/Metered-Dose_Inhaler_%28Adult%29.png": require("./ec505254ce_Metered-Dose_Inhaler__28Adult_29.png"),
  "https://upload.wikimedia.org/wikipedia/commons/3/33/Blausen_0750_PseudostratifiedCiliatedColumnar.png": require("./7489cd31fa_Blausen_0750_PseudostratifiedCiliatedColumnar.png"),
  "https://upload.wikimedia.org/wikipedia/commons/3/33/G-protein-coupled_receptor.png": require("./ce879a3450_G-protein-coupled_receptor.png"),
  "https://upload.wikimedia.org/wikipedia/commons/5/5b/IgE_Fc%CE%B5RI_Receptor_Signal_Cascade.jpg": require("./61755a9db9_IgE_Fc_CE_B5RI_Receptor_Signal_Cascade.jpg"),
  "https://upload.wikimedia.org/wikipedia/commons/6/6b/Asthma.jpg": require("./34ff0fcd3b_Asthma.jpg"),
  "https://upload.wikimedia.org/wikipedia/commons/8/85/Flow-volume-loop.svg": require("./b31e2a8f8a_Flow-volume-loop.svg"),
  "https://upload.wikimedia.org/wikipedia/commons/c/c6/Spirometry_NIH_%28Polish%29.jpg": require("./9708597e1d_Spirometry_NIH__28Polish_29.jpg"),
  "https://upload.wikimedia.org/wikipedia/commons/e/e5/Alveolus_diagram_az.jpg": require("./06ae420fa2_Alveolus_diagram_az.jpg"),
  "https://upload.wikimedia.org/wikipedia/commons/e/eb/Cyclic-adenosine-monophosphate-2D-skeletal.png": require("./e3d7396d34_Cyclic-adenosine-monophosphate-2D-skeletal.png"),
};
